### ISSUE TITLE
Incorrect HAS_ONE example

### ISSUE THREAD

**Issue by fgm** [jinzhu/gorm.io#115]
The example in this new documentation appears to be incorrect, unlike the one in the older version, as explained on https://github.com/jinzhu/gorm/issues/2206 : in short, unlike the BELONGS_TO case, with HAS_ONE (like HAS_MANY), the FK ID is on the owned entity, not on the owner.

In the User/CreditCard example, this means having UserID on CreditCard.

**Comment by fgm** [comment]
Sent PR #116 to fix this

**Comment by emirb** [comment]
Fixed in https://github.com/jinzhu/gorm.io/pull/116
