### ISSUE TITLE
Gorm.io not updated

### ISSUE THREAD

**Issue by emirb** [jinzhu/gorm.io#123]
http://doc.gorm.io/crud.html#query contains a typo (`Assgin`) whereas in master it's already been fixed more than a year ago: https://github.com/jinzhu/gorm.io/blob/aa737260c9d1253f9f5ae355d30bd313a4720ca0/pages/docs/query.md#attrs-1

Is gorm.io automatically updated from master? cc @jinzhu

**Comment by jinzhu** [comment]
Hi @emirb 

doc.gorm.io is not updated, and is abandoned

We switched to gorm.io, and this page . https://gorm.io/docs/
 is auto build from the master branch, let me redirect the URL.
