### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by dennys-bd** [jinzhu/gorm.io#145]
I'd gladly help to translate gorm =D

**Comment by schweigert** [comment]
:tada:

**Comment by psenna** [comment]
I can help to :)

**Comment by schweigert** [comment]
@jinzhu, are you alive?

**Comment by jinzhu** [comment]
Hello @schweigert @dennys-bd 

Sorry for the delay, added.

**Comment by jinzhu** [comment]
Hello @schweigert @dennys-bd 

Could you help to edit this file to add Brazilian Portuguese?

https://github.com/jinzhu/gorm.io/blob/master/pages/_data/languages.yml

**Comment by schweigert** [comment]
:tada:
