### ISSUE TITLE
Too big text on site 

### ISSUE THREAD

**Issue by MikePryadko** [jinzhu/gorm.io#183]
Why text on site so big? And why site have no option to complain??
![D23DBB6F-3D4E-4580-A609-EED2AE757B08](https://user-images.githubusercontent.com/31248040/69478194-e439bf00-0e00-11ea-81e5-c92f056b369a.png)

**Comment by jinzhu** [comment]
Fixed by https://github.com/jinzhu/gorm.io/pull/210

Thank you for your report.
