### ISSUE TITLE
Add Yoruba translation

### ISSUE THREAD

**Issue by mcyusuf** [jinzhu/gorm.io#35]
I would like to partake in translation to Yoruba, one of the major Nigerian languages. Thanks

**Comment by jinzhu** [comment]
Hello @mcyusuf 

Thank you for would like to contribute to GORM!

Have you read the rules added a few days ago from here https://crowdin.com/project/go-gorm?

Which is important to make sure gorm.io's site won't be messed up (already be messed few times, which is annoying for me to correct messed content that I can't understand)

Let me know if you have any questions, thank you!
