### ISSUE TITLE
how to set time.Time default loc and format after query

### ISSUE THREAD

**Issue by heweixi** [jinzhu/gorm.io#99]
when want get gorm query time.Time format as "2018-12-07T10:02:25Z" by default is  "2018-12-07T18:02:25+08:00"
how can set time loc and format after query before return

**Comment by yuntaek** [comment]
There are many timezone names for "+08:00". 
You can set  one as time loc in  "Asiz/Harbin", "Asia/Shanghai","Asia/Chongqing".
If you use mysql dialect with tcp connection, you can set  "user:password@tcp(ip)/databasname"?loc=Asiz/Harbin"
If you want to more timezone list for "+8:00"  visit the site(http://home.kpn.nl/vanadovv/time/TZworld.html#asi).

**Comment by heweixi** [comment]
> There are many timezone names for "+08:00".
> You can set one as time loc in "Asiz/Harbin", "Asia/Shanghai","Asia/Chongqing".
> If you use mysql dialect with tcp connection, you can set "user:password@tcp(ip)/databasname?loc=Asiz/Harbin"
> If you want to more timezone list for "+8:00" visit the site(http://home.kpn.nl/vanadovv/time/TZworld.html#asi).

tks
